# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Optional: A simple script to verify the pipeline starts correctly
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Build and publish the .NET Core web project (customize for your environment if needed)
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

# Deploy to Azure Web App
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MCAPS-Support-REQ-75538-2024-pedromarques(b47f4b5c-a872-40c6-a011-01865fe9dd49)'
    appType: 'webApp'
    WebAppName: 'petedotnetwin'
    deployToSlotOrASE: true
    ResourceGroupName: 'pete_apps_win'
    SlotName: 'test'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    enableCustomDeployment: true
    DeploymentType: 'zipDeploy'
    #swap
    Action: 'Swap Slots'
    SourceSlot: 'dev'
